type TranslateFn = (key: string, params?: Record<string, string | number>) => string

const MESSAGE_MAP: Record<string, string> = {
  '三级分销比例合计必须等于100%': 'settings.invite.commission_distribution.sum_error',
  'Level 1 + Level 2 + Level 3 ratios must equal 100%': 'settings.invite.commission_distribution.sum_error',
  '邮箱或密码错误': 'auth.signIn.invalidCredentials',
  'Incorrect email or password': 'auth.signIn.invalidCredentials',
  '该账户已被停止使用': 'auth.signIn.accountSuspended',
  'Your account has been suspended': 'auth.signIn.accountSuspended',
  '邀请佣金比例必须在0-100之间': 'settings.validation.invite_commission_range',
  '佣金状态不可手动标记为已结算': 'order.messages.commissionSettledManual',
  '已结算的佣金不可回退': 'order.messages.commissionRevertBlocked',
  '订单不存在': 'order.messages.notFound',
  'Order does not exist': 'order.messages.notFound',
  'Order does not exist or has been paid': 'order.messages.notFoundOrPaid',
  '只能对待支付的订单进行操作': 'order.messages.pendingOnly',
  '只能对待支付或处理中的订单进行操作': 'order.messages.cancelPendingOnly',
  '已支付订单不可取消，请先处理退款': 'order.messages.cancelPaidBlocked',
  'You can only cancel pending orders': 'order.messages.cancelPendingOnly',
  'Payment is in progress for this order, cannot cancel': 'order.messages.cancelProcessingBlocked',
  'Cancel failed': 'order.messages.cancelFailed',
  'Payment gateway request failed': 'payment.messages.gatewayFailed',
  '支付网关请求失败': 'payment.messages.gatewayFailed',
  'Telegram Webhook地址未配置': 'settings.telegram.webhookMissing',
  'Telegram Bot Token 未配置': 'settings.telegram.tokenMissing',
  'Telegram Webhook URL is not configured': 'settings.telegram.webhookMissing',
  'Telegram Bot Token is not configured': 'settings.telegram.tokenMissing',
  'Invite commission rate must be between 0 and 100': 'settings.validation.invite_commission_range',
  'Payment method does not exist or is disabled': 'payment.messages.disabled',
  'Payment method does not exist': 'payment.messages.notFound',
  'Configure site URL in settings before adding payment methods': 'payment.messages.siteUrlRequired',
  'Payment method has pending or processing orders and cannot be deleted': 'payment.delete.pendingOrders',
  'Group name cannot be empty': 'group.messages.nameRequired',
  'Group does not exist': 'group.messages.notFound',
  'Group is used by nodes and cannot be deleted': 'group.messages.usedByNodes',
  'Group is used by plans and cannot be deleted': 'group.messages.usedByPlans',
  'Group is used by users and cannot be deleted': 'group.messages.usedByUsers',
  'Route does not exist': 'route.messages.notFound',
  'Remarks cannot be empty': 'route.form.validation.remarks',
  'Match value cannot be empty': 'route.form.validation.match_required',
  'Action type cannot be empty': 'route.form.validation.action_required',
  'Invalid action type': 'route.form.validation.action_invalid',
  'Invalid sort parameters': 'common.invalidSort',
  'Plugin is not enabled': 'plugin.messages.notEnabled',
  '插件未启用': 'plugin.messages.notEnabled',
  'Theme rendering failed. If you updated the theme, settings may have changed — please reconfigure the theme and try again.': 'theme.validation.render_failed',
  '主题渲染失败。如更新主题，参数可能发生变化请重新配置主题后再试。': 'theme.validation.render_failed',
  'Display name cannot be empty': 'payment.form.validation.display_name_required',
  'Gateway parameter cannot be empty': 'payment.form.validation.gateway_required',
  'Config parameter cannot be empty': 'payment.form.validation.config_required',
  'Invalid custom notify domain URL': 'payment.form.validation.notify_domain.url',
  'Invalid fixed handling fee format': 'payment.form.validation.fixed_fee_format',
  'Handling fee percent must be between 0 and 100': 'payment.form.validation.percent_fee_range',
  'Gift card name cannot be empty': 'giftCard.template.form.name.required',
  'Gift card type cannot be empty': 'giftCard.messages.typeEmpty',
  'Invalid gift card type': 'giftCard.messages.typeInvalid',
  'Reward configuration cannot be empty': 'giftCard.messages.rewardRequired',
  'Invalid theme color format': 'giftCard.messages.themeColorInvalid',
  'Background image must be a valid URL': 'settings.validation.background_url',
  'Gift card template is required': 'giftCard.messages.templateRequired',
  'Generation count is required': 'giftCard.messages.countRequired',
  'At most 10000 redemption codes can be generated at once': 'giftCard.messages.countMax',
  'Prefix may only contain uppercase letters and digits': 'giftCard.messages.prefixFormat',
  '组名不能为空': 'group.messages.nameRequired',
  '组不存在': 'group.messages.notFound',
  '该组已被节点所使用，无法删除': 'group.messages.usedByNodes',
  '该组已被订阅所使用，无法删除': 'group.messages.usedByPlans',
  '该组已被用户所使用，无法删除': 'group.messages.usedByUsers',
  '支付方式不存在或未启用': 'payment.messages.disabled',
  '支付方式不存在': 'payment.messages.notFound',
  '请在站点配置中配置站点地址': 'payment.messages.siteUrlRequired',
  '路由不存在': 'route.messages.notFound',
  '邀请人已被封禁，无法设置': 'user.invite.inviterBanned',
  '余额不能为负数': 'user.edit.negativeBalance',
  '佣金余额不能为负数': 'user.edit.negativeCommission',
  '订单开通失败': 'order.assign.createFailed',
  '该用户不存在': 'user.messages.notFound',
  '该订阅不存在': 'user.messages.planNotFound',
  '该用户还有待支付的订单，无法分配': 'order.assign.pendingOrder',
  '该订阅周期不可购买': 'order.assign.invalidPeriod',
  '用户不存在': 'user.messages.notFound',
  '邮箱已被使用': 'user.messages.emailExists',
  '邮箱已存在于系统中': 'user.messages.emailExists',
  '订阅计划不存在': 'user.messages.planNotFound',
  '保存失败': 'user.messages.saveFailed',
  '处理失败': 'user.messages.processingFailed',
  '生成失败': 'user.generate.failed',
  'user_ids不能为空': 'user.messages.userIdsRequired',
  '用户存在待处理的提现工单，请先处理后再删除': 'user.delete.pendingWithdraw',
  '用户存在支付处理中的订单，请等待开通完成或退款后再删除': 'user.delete.pendingOrder',
  '用户仍有站内余额或佣金余额，请先清零后再删除': 'user.delete.nonZeroBalance',
  '无法取消用户未完成订单，请先处理订单后再删除': 'user.delete.openOrders',
  '请提供 email_prefix 或 generate_count': 'user.generate.missingParams',
  '支付金额不能超过订阅标价': 'order.assign.amountExceedsPrice',
  '该订单已有佣金记录，不可重新标记为待确认': 'order.commission.alreadyPaid',
  '该用户已被封禁，无法分配订阅': 'order.assign.userBanned',
  '订单创建失败': 'order.assign.createFailed',
  'Cannot set yourself as inviter': 'user.invite.selfInviter',
  'Invite chain cycle detected': 'user.invite.cycleDetected',
  '优惠券不存在': 'coupon.notFound',
  '不能将自己设为邀请人': 'user.invite.selfInviter',
  '邀请链存在循环，无法设置': 'user.invite.cycleDetected',
  '创建失败': 'giftCard.messages.createFailed',
  '兑换码已过期，无法启用': 'giftCard.messages.codeExpiredEnable',
  '兑换码不存在': 'giftCard.messages.codeNotFound',
  '该礼品卡类型已停用': 'giftCard.messages.templateDisabled',
  '删除失败': 'giftCard.messages.deleteFailed',
  '更新失败': 'giftCard.messages.updateFailed',
  '该模板下存在兑换码，无法删除': 'giftCard.messages.templateHasCodes',
  'Already closed': 'ticket.alreadyClosed',
  'Ticket is already closed': 'ticket.alreadyClosed',
  'Failed to finalize withdraw payout': 'ticket.finalizeWithdrawFailed',
  'Failed to restore withdraw commission': 'ticket.restoreWithdrawFailed',
  'Withdraw ticket requires withdraw_paid or withdraw_rejected': 'ticket.withdrawCloseRequired',
  'Ticket ID cannot be empty': 'ticket.idRequired',
  'Message cannot be empty': 'ticket.messageRequired',
  'Article ID cannot be empty': 'knowledge.idRequired',
  'Invalid parameters': 'common.invalidParameters',
  '工单ID不能为空': 'ticket.idRequired',
  '消息不能为空': 'ticket.messageRequired',
  '知识库ID不能为空': 'knowledge.idRequired',
  '参数有误': 'common.invalidParameters',
  '该支付方式仍有待支付或处理中的订单，无法删除': 'payment.delete.pendingOrders',
  'Template has existing codes and cannot be deleted': 'giftCard.messages.templateHasCodes',
  'Redemption code used cannot be enabled': 'giftCard.messages.codeUsedEnable',
  'Redemption code expired cannot be enabled': 'giftCard.messages.codeExpiredEnable',
  'Operation failed': 'common.operationFailed',
  'Redemption code cannot be reset to unused': 'giftCard.messages.codeResetUnused',
  'Max usage cannot be less than usage count': 'giftCard.messages.maxUsageBelowCount',
  'Used gift card cannot be deleted': 'giftCard.messages.usedCodeDelete',
  'Gift card has usage records and cannot be deleted': 'giftCard.messages.codeHasUsage',
  'Gift card template does not exist': 'giftCard.messages.templateNotFound',
  'Redemption code does not exist': 'giftCard.messages.codeNotFound',
  'This gift card type is disabled': 'giftCard.messages.templateDisabled',
  'Create failed': 'giftCard.messages.createFailed',
  'Update failed': 'giftCard.messages.updateFailed',
  'Delete failed': 'giftCard.messages.deleteFailed',
  'Coupon does not exist': 'coupon.notFound',
  'Coupon ID cannot be empty': 'coupon.idRequired',
  'Coupon ID must be numeric': 'coupon.idNumeric',
  'Inviter does not exist': 'user.invite.inviterNotFound',
  'User ID cannot be empty': 'user.messages.userIdRequired',
  'Inviter is banned and cannot be assigned': 'user.invite.inviterBanned',
  'Save failed': 'user.messages.saveFailed',
  'Generation failed': 'user.generate.failed',
  'Processing failed': 'user.messages.processingFailed',
  'Node does not exist': 'server.manage.messages.notFound',
  'Select nodes to delete': 'server.manage.messages.selectDelete',
  'Batch delete failed': 'server.manage.messages.batchDeleteFailed',
  'Reset failed': 'server.manage.messages.resetFailed',
  'Select nodes to reset traffic': 'server.manage.messages.selectReset',
  'Batch reset failed': 'server.manage.messages.batchResetFailed',
  'Select nodes to update': 'server.manage.messages.selectUpdate',
  'No updatable fields': 'server.manage.messages.noUpdatableFields',
  'Batch update failed': 'server.manage.messages.batchUpdateFailed',
  'Mail template does not exist': 'mailTemplate.messages.notFound',
  'mail_template.missing_placeholder': 'settings.email_template.placeholder_hint',
  'mail_template.unknown': 'mailTemplate.messages.notFound',
  'Server machine does not exist': 'server.machine.messages.notFound',
  'Disable the plugin before uninstalling': 'plugin.messages.disableBeforeUninstall',
  'path parameter cannot be empty': 'plugin.runtime.pageNotFoundDescription',
  'Plugin menu page does not exist': 'plugin.runtime.pageNotFoundDescription',
  'Core plugins cannot be deleted': 'plugin.messages.coreDeleteForbidden',
  'Plugin package file is required': 'plugin.upload.error.format',
  'Plugin package must be a zip file': 'plugin.upload.error.format',
  'Plugin package must not exceed 10MB': 'plugin.upload.error.format',
  'Invalid file type': 'common.invalidFileType',
  'Theme package file is required': 'theme.upload.error.required',
  'Theme package must be a zip file': 'theme.upload.error.format',
  'Theme package must not exceed 10MB': 'theme.upload.error.maxSize',
  'Upload directory is not writable': 'theme.upload.error.uploadDirNotWritable',
  'Theme directory is not writable': 'theme.upload.error.themeDirNotWritable',
  'Invalid file type, only ZIP is supported': 'theme.upload.error.format',
  'Theme package filename may only contain letters, numbers, underscores, hyphens, and dots': 'theme.upload.error.invalidFilename',
  'Node ID cannot be empty': 'server.manage.messages.nodeIdRequired',
  'Local port cannot be empty': 'server.manage.messages.localPortRequired',
  'Failed to fetch node config': 'server.manage.messages.fetchConfigFailed',
  '节点不存在': 'server.manage.messages.notFound',
  '服务器不存在': 'server.manage.messages.notFound',
  '请选择要删除的节点': 'server.manage.messages.selectDelete',
  '批量删除失败': 'server.manage.messages.batchDeleteFailed',
  '重置失败': 'server.manage.messages.resetFailed',
  '请选择要重置的节点': 'server.manage.messages.selectReset',
  '批量重置失败': 'server.manage.messages.batchResetFailed',
  '请选择要更新的节点': 'server.manage.messages.selectUpdate',
  '没有可更新的字段': 'server.manage.messages.noUpdatableFields',
  '批量更新失败': 'server.manage.messages.batchUpdateFailed',
  '模板不存在': 'mailTemplate.messages.notFound',
  '请先禁用插件后再卸载': 'plugin.messages.disableBeforeUninstall',
  '插件菜单页面不存在': 'plugin.runtime.pageNotFoundDescription',
  'path 参数不能为空': 'plugin.runtime.pageNotFoundDescription',
  '该插件为系统核心插件，不允许删除': 'plugin.messages.coreDeleteForbidden',
  'Theme name cannot be empty': 'theme.validation.name_required',
  'Invalid theme name format': 'theme.validation.name_format',
  'Theme config cannot be empty': 'theme.validation.config_required',
  'Plugin code cannot be empty': 'plugin.messages.codeRequired',
  'Payment method ID cannot be empty': 'payment.messages.notFound',
  'Payment method ID format is invalid': 'payment.form.validation.id_format',
  'Gift card template ID cannot be empty': 'giftCard.messages.templateIdEmpty',
  'Gift card template ID format is invalid': 'giftCard.messages.templateIdFormat',
  'Batch ID cannot be empty': 'giftCard.messages.batchIdRequired',
  'Mail template name cannot be empty': 'mailTemplate.messages.notFound',
  'Order ID cannot be empty': 'order.messages.idRequired',
  'Order ID format is invalid': 'order.messages.idFormat',
  'Mystery box reward pool configuration is invalid': 'giftCard.messages.createFailed',
  'Mystery box reward pool cannot be empty': 'giftCard.messages.createFailed',
  'Plan gift card must select a valid plan': 'giftCard.messages.createFailed',
  'Message is too long': 'ticket.messageRequired',
  'Email suffix cannot be empty': 'user.generate.emailSuffixRequired',
  'Payment amount format is invalid': 'order.messages.paymentAmountFormat',
  'Commission status format is invalid': 'order.messages.commissionStatusFormat',
  '邮箱后缀不能为空': 'user.generate.emailSuffixRequired',
  '匹配值不能为空': 'route.form.validation.match_required',
  '动作类型不能为空': 'route.form.validation.action_required',
  '无效的动作类型': 'route.form.validation.action_invalid',
  '订单不存在或已支付': 'order.messages.notFoundOrPaid',
  '取消失败': 'order.messages.cancelFailed',
  '佣金状态格式不正确': 'order.messages.commissionStatusFormat',
  '支付金额格式无效': 'order.messages.paymentAmountFormat',
  '订单ID不能为空': 'order.messages.idRequired',
  '订单ID格式无效': 'order.messages.idFormat',
  'Only pending orders can be marked as paid': 'order.messages.pendingOnly',
  'Only pending or processing orders can be cancelled': 'order.messages.cancelPendingOnly',
  'Paid orders cannot be cancelled; process a refund first': 'order.messages.cancelPaidBlocked',
  'Commission status cannot be manually set to settled': 'order.messages.commissionSettledManual',
  'Settled commission cannot be reverted': 'order.messages.commissionRevertBlocked',
  'Node type cannot be empty': 'server.form.validation.type_required',
  'Invalid node type specified': 'server.form.validation.type_invalid',
  'Node name cannot be empty': 'server.form.validation.name_required',
  'Permission group cannot be empty': 'server.form.validation.group_required',
  'Permission group format is invalid': 'server.form.validation.group_format',
  'Route group format is invalid': 'server.form.validation.route_format',
  'Parent ID format is invalid': 'server.form.validation.parent_id_format',
  'Node host cannot be empty': 'server.form.validation.host_required',
  'Connection port cannot be empty': 'server.form.validation.port_required',
  'Backend port cannot be empty': 'server.form.validation.server_port_required',
  'Tags format is invalid': 'server.form.validation.tags_format',
  'Rate cannot be empty': 'server.form.validation.rate_required',
  'Rate format is invalid': 'server.form.validation.rate_format',
  'Rate time range start time format is invalid (use HH:MM)': 'server.form.validation.rate_time_start_format',
  'Rate time range end time format is invalid (use HH:MM)': 'server.form.validation.rate_time_end_format',
  'Rate multiplier format is invalid': 'server.form.validation.rate_multiplier_format',
  'Rate multiplier cannot be less than 0': 'server.form.validation.rate_multiplier_min',
  'Traffic limit must be an integer': 'server.form.validation.traffic_limit_integer',
  'Traffic limit cannot be less than 0': 'server.form.validation.traffic_limit_min',
  'Plan name cannot be empty': 'subscribe.plan.form.validation.name_required',
  'Plan name cannot exceed 255 characters': 'subscribe.plan.form.validation.name_max',
  'Traffic quota cannot be empty': 'subscribe.plan.form.validation.traffic_required',
  'Traffic quota must be an integer': 'subscribe.plan.form.validation.traffic_integer',
  'Traffic quota must be greater than 0': 'subscribe.plan.form.validation.traffic_min',
  'Price configuration format is invalid': 'subscribe.plan.form.validation.prices_format',
  'Price must be numeric': 'subscribe.plan.form.validation.price_numeric',
  'Price cannot be negative': 'subscribe.plan.form.validation.price_negative',
  'Price must be a number': 'subscribe.plan.form.validation.price_number',
  'Price must be greater than or equal to 0 (leave blank if unused)': 'subscribe.plan.form.validation.price_min_zero',
  'Group ID must be an integer': 'subscribe.plan.form.validation.group_id_integer',
  'Speed limit must be an integer': 'subscribe.plan.form.validation.speed_limit_integer',
  'Speed limit cannot be negative': 'subscribe.plan.form.validation.speed_limit_min',
  'Device limit must be an integer': 'subscribe.plan.form.validation.device_limit_integer',
  'Device limit cannot be negative': 'subscribe.plan.form.validation.device_limit_min',
  'Capacity limit must be an integer': 'subscribe.plan.form.validation.capacity_limit_integer',
  'Capacity limit cannot be negative': 'subscribe.plan.form.validation.capacity_limit_min',
  '节点类型不能为空': 'server.form.validation.type_required',
  '节点类型无效': 'server.form.validation.type_invalid',
  '节点名称不能为空': 'server.form.validation.name_required',
  '权限组不能为空': 'server.form.validation.group_required',
  '权限组格式不正确': 'server.form.validation.group_format',
  '路由组格式不正确': 'server.form.validation.route_format',
  '父ID格式不正确': 'server.form.validation.parent_id_format',
  '连接端口不能为空': 'server.form.validation.port_required',
  '后端服务端口不能为空': 'server.form.validation.server_port_required',
  '倍率不能为空': 'server.form.validation.rate_required',
  '倍率格式不正确': 'server.form.validation.rate_format',
  '动态倍率开始时间格式无效（请使用 HH:MM）': 'server.form.validation.rate_time_start_format',
  '动态倍率结束时间格式无效（请使用 HH:MM）': 'server.form.validation.rate_time_end_format',
  '倍率乘数格式无效': 'server.form.validation.rate_multiplier_format',
  '倍率乘数不能小于 0': 'server.form.validation.rate_multiplier_min',
  '流量上限必须是整数': 'server.form.validation.traffic_limit_integer',
  '流量上限不能小于0': 'server.form.validation.traffic_limit_min',
  '套餐名称不能为空': 'subscribe.plan.form.validation.name_required',
  '套餐名称不能超过 255 个字符': 'subscribe.plan.form.validation.name_max',
  '流量配额不能为空': 'subscribe.plan.form.validation.traffic_required',
  '流量配额必须是整数': 'subscribe.plan.form.validation.traffic_integer',
  '流量配额必须大于 0': 'subscribe.plan.form.validation.traffic_min',
  '价格配置格式不正确': 'subscribe.plan.form.validation.prices_format',
  '价格必须是数字': 'subscribe.plan.form.validation.price_numeric',
  '价格不能为负数': 'subscribe.plan.form.validation.price_negative',
  '价格必须是数字格式': 'subscribe.plan.form.validation.price_number',
  '价格必须大于等于 0（如不需要此周期请留空）': 'subscribe.plan.form.validation.price_min_zero',
  '不支持的订阅周期': 'subscribe.plan.form.validation.period_unsupported',
  'WebSocket URL must include http(s)://': 'settings.validation.websocket_url',
  'Invalid traffic reset method': 'settings.validation.traffic_reset_method_in',
  'Invalid order event type': 'settings.validation.order_event_type_in',
  'Invalid sidebar theme': 'settings.validation.sidebar_theme_in',
  'Invalid header theme': 'settings.validation.header_theme_in',
  'Invalid frontend theme color': 'settings.validation.frontend_theme_color_in',
  'Traffic warning threshold must be between 1 and 100': 'settings.validation.traffic_warn_rate_range',
  'Withdraw ticket stale days must be between 1 and 90': 'settings.validation.withdraw_ticket_stale_range',
  'Withdrawal fee rate must be between 0 and 1': 'settings.validation.withdraw_fee_rate_range',
  'Site URL must include http(s)://': 'settings.validation.app_url_url',
  'Subscribe URL must include http(s)://': 'settings.validation.subscribe_url_url',
  'Server token must be at least 16 characters': 'settings.validation.server_token_min',
  'Terms of service URL must include http(s)://': 'settings.validation.tos_url_url',
  'Telegram webhook URL must include http(s)://': 'settings.validation.telegram_webhook_url_url',
  'Telegram group link must be a valid URL with http(s)://': 'settings.validation.telegram_discuss_link_url',
  'Logo URL must include http(s)://': 'settings.validation.logo_url',
  'Secure admin path must be at least 8 characters': 'settings.validation.secure_path_min',
  'Secure admin path may only contain letters and numbers': 'settings.validation.secure_path_regex',
  'Captcha type must be recaptcha, turnstile, or recaptcha-v3': 'settings.validation.captcha_type_in',
  'reCAPTCHA v3 score threshold must be numeric': 'settings.validation.recaptcha_v3_score_numeric',
  'reCAPTCHA v3 score threshold cannot be less than 0': 'settings.validation.recaptcha_v3_score_min',
  'reCAPTCHA v3 score threshold cannot be greater than 1': 'settings.validation.recaptcha_v3_score_max',
  'Withdrawal fee rate format is invalid': 'settings.validation.withdraw_fee_rate_format',
  'Withdraw ticket stale days format is invalid': 'settings.validation.withdraw_ticket_stale_format',
  'Invite code max uses format is invalid': 'settings.validation.invite_code_max_uses_format',
  'Traffic warning threshold format is invalid': 'settings.validation.traffic_warn_rate_format',
  '站点URL格式不正确，必须携带http(s)://': 'settings.validation.app_url_url',
  '订阅URL格式不正确，必须携带http(s)://': 'settings.validation.subscribe_url_url',
  '通讯密钥长度必须大于16位': 'settings.validation.server_token_min',
  '服务条款URL格式不正确，必须携带http(s)://': 'settings.validation.tos_url_url',
  'Telegram Webhook地址格式不正确，必须携带http(s)://': 'settings.validation.telegram_webhook_url_url',
  'Telegram群组地址必须为URL格式，必须携带http(s)://': 'settings.validation.telegram_discuss_link_url',
  'LOGO URL格式不正确，必须携带http(s)://': 'settings.validation.logo_url',
  '背景图片必须是有效的URL': 'settings.validation.background_url',
  'WebSocket 地址必须包含 http(s)://': 'settings.validation.websocket_url',
  '后台路径长度最小为8位': 'settings.validation.secure_path_min',
  '后台路径只能为字母或数字': 'settings.validation.secure_path_regex',
  '人机验证类型只能选择 recaptcha、turnstile 或 recaptcha-v3': 'settings.validation.captcha_type_in',
  'reCAPTCHA v3 分数阈值必须为数字': 'settings.validation.recaptcha_v3_score_numeric',
  'reCAPTCHA v3 分数阈值不能小于0': 'settings.validation.recaptcha_v3_score_min',
  'reCAPTCHA v3 分数阈值不能大于1': 'settings.validation.recaptcha_v3_score_max',
  '提现费率格式无效': 'settings.validation.withdraw_fee_rate_format',
  '提现费率必须在 0 到 1 之间': 'settings.validation.withdraw_fee_rate_range',
  '提现工单过期天数格式无效': 'settings.validation.withdraw_ticket_stale_format',
  '提现工单过期天数必须在 1 到 90 之间': 'settings.validation.withdraw_ticket_stale_range',
  '邀请码最大使用次数格式无效': 'settings.validation.invite_code_max_uses_format',
  '流量提醒阈值格式无效': 'settings.validation.traffic_warn_rate_format',
  '流量提醒阈值必须在 1 到 100 之间': 'settings.validation.traffic_warn_rate_range',
  '无效的流量重置方式': 'settings.validation.traffic_reset_method_in',
  '无效的订单事件类型': 'settings.validation.order_event_type_in',
  '无效的侧边栏主题': 'settings.validation.sidebar_theme_in',
  '无效的顶栏主题': 'settings.validation.header_theme_in',
  '无效的前端主题色': 'settings.validation.frontend_theme_color_in',
  '显示名称不能为空': 'payment.form.validation.display_name_required',
  '网关参数不能为空': 'payment.form.validation.gateway_required',
  '配置参数不能为空': 'payment.form.validation.config_required',
  '固定手续费格式有误': 'payment.form.validation.fixed_fee_format',
  '百分比手续费范围须在0-100之间': 'payment.form.validation.percent_fee_range',
  '礼品卡类型不能为空': 'giftCard.messages.typeEmpty',
  '无效的礼品卡类型': 'giftCard.messages.typeInvalid',
  '奖励配置不能为空': 'giftCard.messages.rewardRequired',
  '主题色格式不正确': 'giftCard.messages.themeColorInvalid',
  '请选择礼品卡模板': 'giftCard.messages.templateRequired',
  '请指定生成数量': 'giftCard.messages.countRequired',
  '单次最多生成10000个兑换码': 'giftCard.messages.countMax',
  '前缀只能包含大写字母和数字': 'giftCard.messages.prefixFormat',
  '礼品卡模板ID不能为空': 'giftCard.messages.templateIdEmpty',
  '礼品卡模板ID格式无效': 'giftCard.messages.templateIdFormat',
  '批次ID不能为空': 'giftCard.messages.batchIdRequired',
  '主题名称不能为空': 'theme.validation.name_required',
  '主题名称格式无效': 'theme.validation.name_format',
  '主题配置不能为空': 'theme.validation.config_required',
  '插件代码不能为空': 'plugin.messages.codeRequired',
  '支付方式ID格式无效': 'payment.form.validation.id_format',
  '节点 ID 不能为空': 'server.manage.messages.nodeIdRequired',
  '本地端口不能为空': 'server.manage.messages.localPortRequired',
  '获取节点配置失败': 'server.manage.messages.fetchConfigFailed',
  'The user does not exist': 'user.messages.notFound',
  'Email already exists': 'user.messages.emailExists',
  'Subscription plan does not exist': 'user.messages.planNotFound',
  'User IDs cannot be empty': 'user.messages.userIdsRequired',
  'User has an unpaid or pending order, please try again later or cancel it': 'order.assign.pendingOrder',
  'Plan is required': 'order.assign.planRequired',
  'Payment amount cannot be empty': 'order.assign.amountRequired',
  'Subscription period cannot be empty': 'order.assign.periodRequired',
  'Subscription period format is invalid': 'order.assign.periodInvalid',
  'Invalid plan period': 'order.assign.invalidPeriod',
  'Order fulfillment failed': 'order.assign.fulfillmentFailed',
  '订阅不能为空': 'order.assign.planRequired',
  '支付金额不能为空': 'order.assign.amountRequired',
  '订阅周期不能为空': 'order.assign.periodRequired',
  '订阅周期格式有误': 'order.assign.periodInvalid',
  '无效的套餐周期': 'order.assign.invalidPeriod',
  '邮箱已在系统中存在': 'user.messages.emailExists',
  'Title cannot be empty': 'notice.form.validation.title_required',
  'Content cannot be empty': 'notice.form.validation.content_required',
  'Image URL format is invalid': 'notice.form.validation.img_url_format',
  'Tags must be an array': 'notice.form.validation.tags_array',
  '标题不能为空': 'notice.form.validation.title_required',
  '内容不能为空': 'notice.form.validation.content_required',
  '图片URL格式不正确': 'notice.form.validation.img_url_format',
  '标签格式不正确': 'notice.form.validation.tags_array',
  'Name cannot be empty': 'coupon.form.validation.name_required',
  'Coupon type cannot be empty': 'coupon.form.validation.type_required',
  'Coupon type format is invalid': 'coupon.form.validation.type_invalid',
  'Amount or percent cannot be empty': 'coupon.form.validation.value_required',
  'Amount or percent format is invalid': 'coupon.form.validation.value_format',
  'Start time cannot be empty': 'coupon.form.validation.started_at_required',
  'Start time format is invalid': 'coupon.form.validation.started_at_format',
  'End time cannot be empty': 'coupon.form.validation.ended_at_required',
  'End time format is invalid': 'coupon.form.validation.ended_at_format',
  'Max usage format is invalid': 'coupon.form.validation.limit_use_format',
  'Per-user usage limit format is invalid': 'coupon.form.validation.limit_use_with_user_format',
  'Applicable plans must be an array': 'coupon.form.validation.limit_plan_ids_array',
  'Applicable periods must be an array': 'coupon.form.validation.limit_period_array',
  'Generate count must be an integer': 'coupon.form.validation.generate_count_integer',
  'Generate count cannot exceed 500': 'coupon.form.validation.generate_count_max',
  '名称不能为空': 'coupon.form.validation.name_required',
  '类型不能为空': 'coupon.form.validation.type_required',
  '类型格式有误': 'coupon.form.validation.type_invalid',
  '金额或比例不能为空': 'coupon.form.validation.value_required',
  '金额或比例格式有误': 'coupon.form.validation.value_format',
  '开始时间不能为空': 'coupon.form.validation.started_at_required',
  '开始时间格式有误': 'coupon.form.validation.started_at_format',
  '结束时间不能为空': 'coupon.form.validation.ended_at_required',
  '结束时间格式有误': 'coupon.form.validation.ended_at_format',
  '最大使用次数格式有误': 'coupon.form.validation.limit_use_format',
  '限制用户使用次数格式有误': 'coupon.form.validation.limit_use_with_user_format',
  '指定订阅格式有误': 'coupon.form.validation.limit_plan_ids_array',
  '指定周期格式有误': 'coupon.form.validation.limit_period_array',
  '生成数量必须为数字': 'coupon.form.validation.generate_count_integer',
  '生成数量最大为500个': 'coupon.form.validation.generate_count_max',
  'Category cannot be empty': 'knowledge.validation.category_required',
  'Language cannot be empty': 'knowledge.validation.language_required',
  'Invalid knowledge language': 'knowledge.validation.language_invalid',
  'Display status must be boolean': 'knowledge.validation.show_boolean',
  'Category name cannot be empty': 'knowledge.validation.category_name_required',
  'Category language cannot be empty': 'knowledge.validation.category_language_required',
  'Knowledge IDs cannot be empty': 'knowledge.validation.ids_required',
  'Knowledge ID format is invalid': 'knowledge.validation.ids_format',
  'Category list cannot be empty': 'knowledge.validation.category_list_required',
  'Category format is invalid': 'knowledge.validation.category_list_format',
  '分类不能为空': 'knowledge.validation.category_required',
  '语言不能为空': 'knowledge.validation.language_required',
  '知识库语言无效': 'knowledge.validation.language_invalid',
  '显示状态必须为布尔值': 'knowledge.validation.show_boolean',
  '分类名称不能为空': 'knowledge.validation.category_name_required',
  '分类语言不能为空': 'knowledge.validation.category_language_required',
  '知识ID不能为空': 'knowledge.validation.ids_required',
  '知识ID格式有误': 'knowledge.validation.ids_format',
  '分类列表不能为空': 'knowledge.validation.category_list_required',
  '分类格式有误': 'knowledge.validation.category_list_format',
  'Send type cannot be empty': 'mail.validation.type_required',
  'Send type format is invalid': 'mail.validation.type_invalid',
  'Email subject cannot be empty': 'mail.validation.subject_required',
  'Recipients must be an array': 'mail.validation.receiver_array',
  'Mail content cannot be empty': 'user.send_mail.validation.content_required',
  '发送类型不能为空': 'mail.validation.type_required',
  '发送类型格式有误': 'mail.validation.type_invalid',
  '主题不能为空': 'mail.validation.subject_required',
  '发送内容不能为空': 'user.send_mail.validation.content_required',
  '收件人格式有误': 'mail.validation.receiver_array',
  'Email cannot be empty': 'user.edit.validation.email_required',
  'Email format is invalid': 'user.edit.validation.email_format',
  'Traffic format is invalid': 'user.edit.validation.traffic_format',
  'Expiry time format is invalid': 'user.edit.validation.expired_at_format',
  'Ban status format is invalid': 'user.edit.validation.ban_status_format',
  'Admin status cannot be empty': 'user.edit.validation.admin_status_required',
  'Admin status format is invalid': 'user.edit.validation.admin_status_format',
  'Staff status cannot be empty': 'user.edit.validation.staff_status_required',
  'Staff status format is invalid': 'user.edit.validation.staff_status_format',
  'Plan format is invalid': 'user.edit.validation.plan_format',
  'Commission rate format is invalid': 'user.edit.validation.commission_rate_format',
  'Commission rate must be at least 0': 'user.edit.validation.commission_rate_min',
  'Commission rate cannot exceed 100': 'user.edit.validation.commission_rate_max',
  'Discount rate format is invalid': 'user.edit.validation.discount_rate_format',
  'Discount rate must be at least 0': 'user.edit.validation.discount_rate_min',
  'Discount rate cannot exceed 100': 'user.edit.validation.discount_rate_max',
  'Upload traffic format is invalid': 'user.edit.validation.upload_traffic_format',
  'Download traffic format is invalid': 'user.edit.validation.download_traffic_format',
  'Balance format is invalid': 'user.edit.validation.balance_format',
  'Commission balance format is invalid': 'user.edit.validation.commission_balance_format',
  'Password must be at least 8 characters': 'user.edit.validation.password_min',
  'Speed limit format is invalid': 'user.edit.validation.speed_limit_format',
  'Device limit format is invalid': 'user.edit.validation.device_limit_format',
  '邮箱不能为空': 'user.edit.validation.email_required',
  '邮箱格式不正确': 'user.edit.validation.email_format',
  '流量格式不正确': 'user.edit.validation.traffic_format',
  '到期时间格式不正确': 'user.edit.validation.expired_at_format',
  '是否封禁格式不正确': 'user.edit.validation.ban_status_format',
  '是否管理员不能为空': 'user.edit.validation.admin_status_required',
  '是否管理员格式不正确': 'user.edit.validation.admin_status_format',
  '是否员工不能为空': 'user.edit.validation.staff_status_required',
  '是否员工格式不正确': 'user.edit.validation.staff_status_format',
  '订阅计划格式不正确': 'user.edit.validation.plan_format',
  '推荐返利比例格式不正确': 'user.edit.validation.commission_rate_format',
  '推荐返利比例最小为0': 'user.edit.validation.commission_rate_min',
  '推荐返利比例最大为100': 'user.edit.validation.commission_rate_max',
  '专属折扣比例格式不正确': 'user.edit.validation.discount_rate_format',
  '专属折扣比例最小为0': 'user.edit.validation.discount_rate_min',
  '专属折扣比例最大为100': 'user.edit.validation.discount_rate_max',
  '上行流量格式不正确': 'user.edit.validation.upload_traffic_format',
  '下行流量格式不正确': 'user.edit.validation.download_traffic_format',
  '余额格式不正确': 'user.edit.validation.balance_format',
  '佣金格式不正确': 'user.edit.validation.commission_balance_format',
  '密码长度最小8位': 'user.edit.validation.password_min',
  '限速格式不正确': 'user.edit.validation.speed_limit_format',
  '设备数量格式不正确': 'user.edit.validation.device_limit_format',
  'Plan IDs cannot be empty': 'subscribe.plan.sortValidation.ids_required',
  'Plan ID format is invalid': 'subscribe.plan.sortValidation.id_format',
  '订阅计划ID不能为空': 'subscribe.plan.sortValidation.ids_required',
  '订阅计划ID格式有误': 'subscribe.plan.sortValidation.id_format',
  'Ban status cannot be empty': 'user.edit.validation.ban_status_required',
  '是否封禁不能为空': 'user.edit.validation.ban_status_required',
  'Filter key cannot be empty': 'user.filter.validation.key_required',
  'Invalid filter key': 'user.filter.validation.key_invalid',
  'Filter condition cannot be empty': 'user.filter.validation.condition_required',
  'Invalid filter condition': 'user.filter.validation.condition_invalid',
  'Filter value cannot be empty': 'user.filter.validation.value_required',
  '筛选键不能为空': 'user.filter.validation.key_required',
  '过滤键不能为空': 'user.filter.validation.key_required',
  '过滤键参数有误': 'user.filter.validation.key_invalid',
  '过滤条件不能为空': 'user.filter.validation.condition_required',
  '过滤条件参数有误': 'user.filter.validation.condition_invalid',
  '过滤值不能为空': 'user.filter.validation.value_required',
  '筛选键无效': 'user.filter.validation.key_invalid',
  '筛选条件不能为空': 'user.filter.validation.condition_required',
  '筛选条件无效': 'user.filter.validation.condition_invalid',
  '筛选值不能为空': 'user.filter.validation.value_required',
  'Sales status format is invalid': 'subscribe.plan.updateValidation.show_format',
  'Renewal status format is invalid': 'subscribe.plan.updateValidation.renew_format',
  '销售状态格式有误': 'subscribe.plan.updateValidation.show_format',
  '销售状态格式不正确': 'subscribe.plan.updateValidation.show_format',
  '续费状态格式有误': 'subscribe.plan.updateValidation.renew_format',
  '续费状态格式不正确': 'subscribe.plan.updateValidation.renew_format',
  'Trade number cannot be empty': 'order.messages.tradeNoRequired',
  '订单号不能为空': 'order.messages.tradeNoRequired',
}

type AdminErrorPattern = {
  test: (message: string) => boolean
  key: string
  params?: (message: string) => Record<string, string | number> | undefined
}

const ERROR_PATTERNS: AdminErrorPattern[] = [
  {
    test: (m) => /^The .+ field is required$/.test(m),
    key: 'server.form.validation.field_required',
    params: (m) => {
      const hit = m.match(/^The (.+) field is required$/)
      return hit ? { field: hit[1] } : undefined
    },
  },
  {
    test: (m) => /^The .+ field must be a string$/.test(m),
    key: 'server.form.validation.field_string',
    params: (m) => {
      const hit = m.match(/^The (.+) field must be a string$/)
      return hit ? { field: hit[1] } : undefined
    },
  },
  {
    test: (m) => /^The .+ field must be an integer$/.test(m),
    key: 'server.form.validation.field_integer',
    params: (m) => {
      const hit = m.match(/^The (.+) field must be an integer$/)
      return hit ? { field: hit[1] } : undefined
    },
  },
  {
    test: (m) => /^The .+ field has an invalid value$/.test(m),
    key: 'server.form.validation.field_invalid',
    params: (m) => {
      const hit = m.match(/^The (.+) field has an invalid value$/)
      return hit ? { field: hit[1] } : undefined
    },
  },
]

const MESSAGE_PREFIX_MAP: Array<[string, string]> = [
  ['Plugin install failed:', 'plugin.messages.installError'],
  ['Plugin uninstall failed:', 'plugin.messages.uninstallError'],
  ['Plugin upgrade failed:', 'plugin.messages.upgradeError'],
  ['Plugin enable failed:', 'plugin.messages.enableError'],
  ['Plugin disable failed:', 'plugin.messages.disableError'],
  ['Failed to load plugin config:', 'plugin.messages.configLoadError'],
  ['Plugin config update failed:', 'plugin.messages.configSaveError'],
  ['Plugin upload failed:', 'plugin.messages.uploadError'],
  ['Plugin delete failed:', 'plugin.messages.deleteError'],
  ['Theme upload failed:', 'theme.upload.error.uploadFailed'],
  ['Mystery box reward pool item ', 'giftCard.messages.createFailed'],
  ['盲盒奖池第 ', 'giftCard.messages.createFailed'],
  ['插件安装失败：', 'plugin.messages.installError'],
  ['插件卸载失败：', 'plugin.messages.uninstallError'],
  ['插件升级失败：', 'plugin.messages.upgradeError'],
  ['插件启用失败：', 'plugin.messages.enableError'],
  ['插件禁用失败：', 'plugin.messages.disableError'],
  ['获取配置失败：', 'plugin.messages.configLoadError'],
  ['配置更新失败：', 'plugin.messages.configSaveError'],
  ['插件上传失败：', 'plugin.messages.uploadError'],
  ['插件删除失败：', 'plugin.messages.deleteError'],
  ['发送失败:', 'mailTemplate.messages.sendFailed'],
  ['Unsupported subscription period:', 'subscribe.plan.form.validation.period_unsupported'],
  ['不支持的订阅周期：', 'subscribe.plan.form.validation.period_unsupported'],
]

function extractMessage(error: unknown): string {
  if (error instanceof Error) return error.message
  if (typeof error === 'string') return error
  return ''
}

export function resolveApiError(error: unknown, t: TranslateFn, fallback?: string): string {
  const raw = extractMessage(error).trim()
  if (!raw) return fallback ?? t('common.error')
  const key = MESSAGE_MAP[raw]
  if (key) return t(key)
  for (const [prefix, i18nKey] of MESSAGE_PREFIX_MAP) {
    if (raw.startsWith(prefix)) return t(i18nKey)
  }
  for (const pattern of ERROR_PATTERNS) {
    if (pattern.test(raw)) {
      const params = pattern.params?.(raw)
      return t(pattern.key, params)
    }
  }
  return raw
}

type ToastLike = { error: (message: string) => void }

/** Show a translated API error in admin toasts (maps known backend messages to i18n keys). */
export function toastApiError(
  error: unknown,
  toast: ToastLike,
  t: TranslateFn,
  fallback?: string,
): void {
  toast.error(resolveApiError(error, t, fallback))
}
