type TranslateFn = (key: string, params?: Record<string, string | number>) => string

const MESSAGE_MAP: Record<string, string> = {
  '三级分销比例合计必须等于100%': 'settings.invite.commission_distribution.sum_error',
  'Level 1 + Level 2 + Level 3 ratios must equal 100%': 'settings.invite.commission_distribution.sum_error',
  '邮箱或密码错误': 'auth.signIn.invalidCredentials',
  'Incorrect email or password': 'auth.signIn.invalidCredentials',
  '该账户已被停止使用': 'auth.signIn.accountSuspended',
  'Your account has been suspended': 'auth.signIn.accountSuspended',
  '邀请佣金比例必须在0-100之间': 'common.error',
  '佣金状态不可手动标记为已结算': 'common.error',
  '已结算的佣金不可回退': 'common.error',
  '订单不存在': 'common.error',
  'Order does not exist': 'common.error',
  'Order does not exist or has been paid': 'common.error',
  '只能对待支付的订单进行操作': 'common.error',
  '只能对待支付或处理中的订单进行操作': 'common.error',
  '已支付订单不可取消，请先处理退款': 'common.error',
  'You can only cancel pending orders': 'common.error',
  'Payment is in progress for this order, cannot cancel': 'common.error',
  'Cancel failed': 'common.error',
  'Payment gateway request failed': 'common.error',
  'Telegram Webhook地址未配置': 'settings.telegram.webhookMissing',
  'Telegram Bot Token 未配置': 'settings.telegram.tokenMissing',
  'Telegram Webhook URL is not configured': 'settings.telegram.webhookMissing',
  'Telegram Bot Token is not configured': 'settings.telegram.tokenMissing',
  'Invite commission rate must be between 0 and 100': 'common.error',
  'Payment method does not exist or is disabled': 'payment.messages.disabled',
  'Payment method does not exist': 'payment.messages.notFound',
  'Configure site URL in settings before adding payment methods': 'payment.messages.siteUrlRequired',
  'Payment method has pending or processing orders and cannot be deleted': 'payment.delete.pendingOrders',
  'Group name cannot be empty': 'group.messages.nameRequired',
  'Group does not exist': 'group.messages.notFound',
  'Group is used by nodes and cannot be deleted': 'group.messages.usedByNodes',
  'Group is used by plans and cannot be deleted': 'group.messages.usedByPlans',
  'Group is used by users and cannot be deleted': 'group.messages.usedByUsers',
  'Route does not exist': 'route.messages.notFound',
  'Remarks cannot be empty': 'route.form.validation.remarks',
  'Match value cannot be empty': 'common.error',
  'Action type cannot be empty': 'common.error',
  'Invalid action type': 'common.error',
  'Invalid sort parameters': 'common.error',
  'Display name cannot be empty': 'common.error',
  'Gateway parameter cannot be empty': 'common.error',
  'Config parameter cannot be empty': 'common.error',
  'Invalid custom notify domain URL': 'payment.form.validation.notify_domain.url',
  'Invalid fixed handling fee format': 'common.error',
  'Handling fee percent must be between 0 and 100': 'common.error',
  'Gift card name cannot be empty': 'giftCard.template.form.name.required',
  'Gift card type cannot be empty': 'common.error',
  'Invalid gift card type': 'common.error',
  'Reward configuration cannot be empty': 'common.error',
  'Invalid theme color format': 'common.error',
  'Background image must be a valid URL': 'common.error',
  'Gift card template is required': 'common.error',
  'Generation count is required': 'common.error',
  'At most 10000 redemption codes can be generated at once': 'common.error',
  'Prefix may only contain uppercase letters and digits': 'common.error',
  '组名不能为空': 'group.messages.nameRequired',
  '组不存在': 'group.messages.notFound',
  '该组已被节点所使用，无法删除': 'group.messages.usedByNodes',
  '该组已被订阅所使用，无法删除': 'group.messages.usedByPlans',
  '该组已被用户所使用，无法删除': 'group.messages.usedByUsers',
  '支付方式不存在或未启用': 'payment.messages.disabled',
  '支付方式不存在': 'payment.messages.notFound',
  '请在站点配置中配置站点地址': 'payment.messages.siteUrlRequired',
  '路由不存在': 'route.messages.notFound',
  '保存失败': 'common.error',
  '创建失败': 'giftCard.messages.createFailed',
  '邀请人已被封禁，无法设置': 'user.invite.inviterBanned',
  '余额不能为负数': 'user.edit.negativeBalance',
  '佣金余额不能为负数': 'user.edit.negativeCommission',
  '不能将自己设为邀请人': 'user.invite.selfInviter',
  '邀请链存在循环，无法设置': 'user.invite.cycleDetected',
  '订单开通失败': 'order.assign.createFailed',
  '该用户不存在': 'common.error',
  '该订阅不存在': 'common.error',
  '该用户还有待支付的订单，无法分配': 'common.error',
  '该订阅周期不可购买': 'common.error',
  '用户不存在': 'common.error',
  '邮箱已被使用': 'common.error',
  '邮箱已存在于系统中': 'common.error',
  '订阅计划不存在': 'common.error',
  '保存失败': 'common.error',
  '更新失败': 'common.error',
  '处理失败': 'common.error',
  '生成失败': 'common.error',
  'user_ids不能为空': 'common.error',
  '用户存在待处理的提现工单，请先处理后再删除': 'user.delete.pendingWithdraw',
  '用户存在支付处理中的订单，请等待开通完成或退款后再删除': 'user.delete.pendingOrder',
  '用户仍有站内余额或佣金余额，请先清零后再删除': 'user.delete.nonZeroBalance',
  '无法取消用户未完成订单，请先处理订单后再删除': 'user.delete.openOrders',
  '删除失败': 'user.delete.failed',
  '请提供 email_prefix 或 generate_count': 'user.generate.missingParams',
  '支付金额不能超过订阅标价': 'order.assign.amountExceedsPrice',
  '该订单已有佣金记录，不可重新标记为待确认': 'order.commission.alreadyPaid',
  '该用户已被封禁，无法分配订阅': 'order.assign.userBanned',
  '订单创建失败': 'order.assign.createFailed',
  'Cannot set yourself as inviter': 'user.invite.selfInviter',
  'Invite chain cycle detected': 'user.invite.cycleDetected',
  '优惠券不存在': 'coupon.notFound',
  '不能将自己设为邀请人': 'user.invite.selfInviter',
  '邀请链存在循环，无法设置': 'user.invite.cycleDetected',
  '创建失败': 'giftCard.messages.createFailed',
  '模板不存在': 'giftCard.messages.templateNotFound',
  '兑换码已过期，无法启用': 'giftCard.messages.codeExpiredEnable',
  '兑换码不存在': 'giftCard.messages.codeNotFound',
  '该礼品卡类型已停用': 'giftCard.messages.templateDisabled',
  '删除失败': 'giftCard.messages.deleteFailed',
  '更新失败': 'giftCard.messages.updateFailed',
  '该模板下存在兑换码，无法删除': 'giftCard.messages.templateHasCodes',
  'Already closed': 'ticket.alreadyClosed',
  'Ticket is already closed': 'ticket.alreadyClosed',
  'Failed to finalize withdraw payout': 'ticket.finalizeWithdrawFailed',
  'Failed to restore withdraw commission': 'ticket.restoreWithdrawFailed',
  'Withdraw ticket requires withdraw_paid or withdraw_rejected': 'ticket.withdrawCloseRequired',
  'Ticket ID cannot be empty': 'ticket.idRequired',
  'Message cannot be empty': 'ticket.messageRequired',
  'Article ID cannot be empty': 'knowledge.idRequired',
  'Invalid parameters': 'common.invalidParameters',
  '工单ID不能为空': 'ticket.idRequired',
  '消息不能为空': 'ticket.messageRequired',
  '知识库ID不能为空': 'knowledge.idRequired',
  '参数有误': 'common.invalidParameters',
  '该支付方式仍有待支付或处理中的订单，无法删除': 'payment.delete.pendingOrders',
  'Template has existing codes and cannot be deleted': 'giftCard.messages.templateHasCodes',
  'Redemption code used cannot be enabled': 'giftCard.messages.codeUsedEnable',
  'Redemption code expired cannot be enabled': 'giftCard.messages.codeExpiredEnable',
  'Operation failed': 'common.error',
  'Redemption code cannot be reset to unused': 'giftCard.messages.codeResetUnused',
  'Max usage cannot be less than usage count': 'giftCard.messages.maxUsageBelowCount',
  'Used gift card cannot be deleted': 'giftCard.messages.usedCodeDelete',
  'Gift card has usage records and cannot be deleted': 'giftCard.messages.codeHasUsage',
  'Gift card template does not exist': 'giftCard.messages.templateNotFound',
  'Redemption code does not exist': 'giftCard.messages.codeNotFound',
  'This gift card type is disabled': 'giftCard.messages.templateDisabled',
  'Create failed': 'giftCard.messages.createFailed',
  'Update failed': 'giftCard.messages.updateFailed',
  'Delete failed': 'giftCard.messages.deleteFailed',
  'Coupon does not exist': 'coupon.notFound',
  'Coupon ID cannot be empty': 'coupon.idRequired',
  'Coupon ID must be numeric': 'coupon.idNumeric',
  'Inviter does not exist': 'user.invite.inviterNotFound',
  'User ID cannot be empty': 'common.error',
  'Inviter is banned and cannot be assigned': 'user.invite.inviterBanned',
  'Save failed': 'common.error',
  'Generation failed': 'user.generate.failed',
  'Processing failed': 'common.error',
  'Node does not exist': 'server.manage.messages.notFound',
  'Select nodes to delete': 'server.manage.messages.selectDelete',
  'Batch delete failed': 'server.manage.messages.batchDeleteFailed',
  'Reset failed': 'server.manage.messages.resetFailed',
  'Select nodes to reset traffic': 'server.manage.messages.selectReset',
  'Batch reset failed': 'server.manage.messages.batchResetFailed',
  'Select nodes to update': 'server.manage.messages.selectUpdate',
  'No updatable fields': 'server.manage.messages.noUpdatableFields',
  'Batch update failed': 'server.manage.messages.batchUpdateFailed',
  'Mail template does not exist': 'mailTemplate.messages.notFound',
  'mail_template.missing_placeholder': 'settings.email_template.placeholder_hint',
  'mail_template.unknown': 'mailTemplate.messages.notFound',
  'Server machine does not exist': 'server.machine.messages.notFound',
  'Disable the plugin before uninstalling': 'plugin.messages.disableBeforeUninstall',
  'path parameter cannot be empty': 'plugin.runtime.pageNotFoundDescription',
  'Plugin menu page does not exist': 'plugin.runtime.pageNotFoundDescription',
  'Core plugins cannot be deleted': 'plugin.messages.coreDeleteForbidden',
  'Plugin package file is required': 'plugin.upload.error.format',
  'Plugin package must be a zip file': 'plugin.upload.error.format',
  'Plugin package must not exceed 10MB': 'plugin.upload.error.format',
  'Invalid file type': 'common.error',
  'Theme package file is required': 'theme.upload.error.required',
  'Theme package must be a zip file': 'theme.upload.error.format',
  'Theme package must not exceed 10MB': 'theme.upload.error.maxSize',
  'Upload directory is not writable': 'theme.upload.error.uploadDirNotWritable',
  'Theme directory is not writable': 'theme.upload.error.themeDirNotWritable',
  'Invalid file type, only ZIP is supported': 'theme.upload.error.format',
  'Theme package filename may only contain letters, numbers, underscores, hyphens, and dots': 'theme.upload.error.invalidFilename',
  'Node ID cannot be empty': 'common.error',
  'Local port cannot be empty': 'common.error',
  'Failed to fetch node config': 'common.error',
  '节点不存在': 'server.manage.messages.notFound',
  '服务器不存在': 'server.manage.messages.notFound',
  '请选择要删除的节点': 'server.manage.messages.selectDelete',
  '批量删除失败': 'server.manage.messages.batchDeleteFailed',
  '重置失败': 'server.manage.messages.resetFailed',
  '请选择要重置的节点': 'server.manage.messages.selectReset',
  '批量重置失败': 'server.manage.messages.batchResetFailed',
  '请选择要更新的节点': 'server.manage.messages.selectUpdate',
  '没有可更新的字段': 'server.manage.messages.noUpdatableFields',
  '批量更新失败': 'server.manage.messages.batchUpdateFailed',
  '模板不存在': 'mailTemplate.messages.notFound',
  '请先禁用插件后再卸载': 'plugin.messages.disableBeforeUninstall',
  '插件菜单页面不存在': 'plugin.runtime.pageNotFoundDescription',
  'path 参数不能为空': 'plugin.runtime.pageNotFoundDescription',
  '该插件为系统核心插件，不允许删除': 'plugin.messages.coreDeleteForbidden',
}

const MESSAGE_PREFIX_MAP: Array<[string, string]> = [
  ['Plugin install failed:', 'plugin.messages.installError'],
  ['Plugin uninstall failed:', 'plugin.messages.uninstallError'],
  ['Plugin upgrade failed:', 'plugin.messages.upgradeError'],
  ['Plugin enable failed:', 'plugin.messages.enableError'],
  ['Plugin disable failed:', 'plugin.messages.disableError'],
  ['Failed to load plugin config:', 'plugin.messages.configLoadError'],
  ['Plugin config update failed:', 'plugin.messages.configSaveError'],
  ['Plugin upload failed:', 'plugin.messages.uploadError'],
  ['Plugin delete failed:', 'plugin.messages.deleteError'],
  ['Theme upload failed:', 'theme.upload.error.uploadFailed'],
  ['Send failed:', 'mailTemplate.messages.sendFailed'],
  ['插件安装失败：', 'plugin.messages.installError'],
  ['插件卸载失败：', 'plugin.messages.uninstallError'],
  ['插件升级失败：', 'plugin.messages.upgradeError'],
  ['插件启用失败：', 'plugin.messages.enableError'],
  ['插件禁用失败：', 'plugin.messages.disableError'],
  ['获取配置失败：', 'plugin.messages.configLoadError'],
  ['配置更新失败：', 'plugin.messages.configSaveError'],
  ['插件上传失败：', 'plugin.messages.uploadError'],
  ['插件删除失败：', 'plugin.messages.deleteError'],
  ['发送失败:', 'mailTemplate.messages.sendFailed'],
]

function extractMessage(error: unknown): string {
  if (error instanceof Error) return error.message
  if (typeof error === 'string') return error
  return ''
}

export function resolveApiError(error: unknown, t: TranslateFn, fallback?: string): string {
  const raw = extractMessage(error).trim()
  if (!raw) return fallback ?? t('common.error')
  const key = MESSAGE_MAP[raw]
  if (key) return t(key)
  for (const [prefix, i18nKey] of MESSAGE_PREFIX_MAP) {
    if (raw.startsWith(prefix)) return t(i18nKey)
  }
  return raw
}

type ToastLike = { error: (message: string) => void }

/** Show a translated API error in admin toasts (maps known backend messages to i18n keys). */
export function toastApiError(
  error: unknown,
  toast: ToastLike,
  t: TranslateFn,
  fallback?: string,
): void {
  toast.error(resolveApiError(error, t, fallback))
}
